version: 0.0
os: linux
files:
  - source: target/DevOpsSummative-1.0-SNAPSHOT.jar
    destination: /home/ec2-user/app
  - source: scripts/deploy.sh
    destination: /home/ec2-user/scripts

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
